// <auto-generated />
using Animal;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Animal.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Animal.Animal", b =>
                {
                    b.Property<int>("id_Animal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("edad")
                        .HasColumnType("int");

                    b.Property<double>("peso")
                        .HasColumnType("float");

                    b.Property<int>("tipo_Raza")
                        .HasColumnType("int");

                    b.HasKey("id_Animal");

                    b.ToTable("Animal");
                });

            modelBuilder.Entity("Animal.Comida", b =>
                {
                    b.Property<int>("id_Comida")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descripcion_Comida")
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Nombre_Comida")
                        .HasColumnType("varchar(50)");

                    b.HasKey("id_Comida");

                    b.ToTable("Comida");
                });

            modelBuilder.Entity("Animal.Juguete", b =>
                {
                    b.Property<int>("id_Juguete")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descripcion_Juguete")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Nombre_Juguete")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("id_Juguete");

                    b.ToTable("Juguete");
                });

            modelBuilder.Entity("Animal.Pedido", b =>
                {
                    b.Property<int>("id_Pedido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion_Pedido")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<int>("Id_Producto")
                        .HasColumnType("int");

                    b.HasKey("id_Pedido");

                    b.ToTable("Pedido");
                });

            modelBuilder.Entity("Animal.Producto", b =>
                {
                    b.Property<int>("id_Producto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descripcion_Producto")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<int>("Id_Asignado")
                        .HasColumnType("int");

                    b.Property<string>("Tipo_Producto")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("id_Producto");

                    b.ToTable("Producto");
                });

            modelBuilder.Entity("Animal.Raza", b =>
                {
                    b.Property<int>("id_Raza")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descripcion_Raza")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Nombre_Raza")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("id_Raza");

                    b.ToTable("Raza");
                });

            modelBuilder.Entity("Animal.ordenar_Pedido", b =>
                {
                    b.Property<int>("id_Ordernar")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("id_Producto")
                        .HasColumnType("int");

                    b.HasKey("id_Ordernar");

                    b.ToTable("Ordenar_Pedido");
                });
#pragma warning restore 612, 618
        }
    }
}
